"""initial_schema

Revision ID: 9ed9487c073e
Revises: 
Create Date: 2026-06-04 11:12:17.731585

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ed9487c073e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('tweet_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scrape_depth', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'username', name='uq_account_platform_username')
    )
    op.create_index('ix_account_scrape_depth', 'account', ['scrape_depth'], unique=False)
    op.create_index('ix_account_scraped_at', 'account', ['scraped_at'], unique=False)
    op.create_table('crawl_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seed_username', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('max_accounts', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_status_enum'), nullable=False),
    sa.Column('accounts_scraped', sa.Integer(), nullable=False),
    sa.Column('accounts_queued', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crawl_job_created_at', 'crawl_job', ['created_at'], unique=False)
    op.create_index('ix_crawl_job_status', 'crawl_job', ['status'], unique=False)
    op.create_table('proxy_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proxy_record_host_port', 'proxy_record', ['host', 'port'], unique=False)
    op.create_index('ix_proxy_record_is_alive', 'proxy_record', ['is_alive'], unique=False)
    op.create_index('ix_proxy_record_last_used_at', 'proxy_record', ['last_used_at'], unique=False)
    op.create_table('cross_platform_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('target_platform', sa.String(), nullable=False),
    sa.Column('target_handle', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_field', sa.Enum('BIO', 'WEBSITE', 'PINNED_TWEET', 'TWEET_BODY', name='source_field_enum'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cross_platform_link_account_id', 'cross_platform_link', ['account_id'], unique=False)
    op.create_index('ix_cross_platform_link_target_platform', 'cross_platform_link', ['target_platform'], unique=False)
    op.create_table('job_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_event_job_id', 'job_event', ['job_id'], unique=False)
    op.create_index('ix_job_event_job_id_sequence', 'job_event', ['job_id', 'sequence'], unique=False)
    op.create_table('job_queue_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'SKIPPED', name='queue_item_status_enum'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_queue_item_job_id', 'job_queue_item', ['job_id'], unique=False)
    op.create_index('ix_job_queue_item_priority', 'job_queue_item', ['priority'], unique=False)
    op.create_index('ix_job_queue_item_status', 'job_queue_item', ['status'], unique=False)
    op.create_table('raw_scrape_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('scrape_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('raw_html', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('parsed', sa.Boolean(), nullable=False),
    sa.Column('parse_error', sa.String(), nullable=True),
    sa.Column('proxy_used', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_job.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_scrape_result_account_id', 'raw_scrape_result', ['account_id'], unique=False)
    op.create_index('ix_raw_scrape_result_job_id', 'raw_scrape_result', ['job_id'], unique=False)
    op.create_index('ix_raw_scrape_result_parsed', 'raw_scrape_result', ['parsed'], unique=False)
    op.create_index('ix_raw_scrape_result_scraped_at', 'raw_scrape_result', ['scraped_at'], unique=False)
    op.create_index('ix_raw_scrape_result_username', 'raw_scrape_result', ['username'], unique=False)
    op.create_table('relationship',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_account_id', sa.Uuid(), nullable=False),
    sa.Column('target_account_id', sa.Uuid(), nullable=False),
    sa.Column('rel_type', sa.Enum('FOLLOWS', 'MENTIONS', 'REPLIES_TO', 'QUOTE_TWEETS', 'CROSS_PLATFORM_LINK', name='rel_type_enum'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('_metadata', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['source_account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_account_id', 'target_account_id', 'rel_type', name='uq_relationship_source_target_type')
    )
    op.create_index('ix_relationship_rel_type', 'relationship', ['rel_type'], unique=False)
    op.create_index('ix_relationship_source_account_id', 'relationship', ['source_account_id'], unique=False)
    op.create_index('ix_relationship_target_account_id', 'relationship', ['target_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationship_target_account_id', table_name='relationship')
    op.drop_index('ix_relationship_source_account_id', table_name='relationship')
    op.drop_index('ix_relationship_rel_type', table_name='relationship')
    op.drop_table('relationship')
    op.drop_index('ix_raw_scrape_result_username', table_name='raw_scrape_result')
    op.drop_index('ix_raw_scrape_result_scraped_at', table_name='raw_scrape_result')
    op.drop_index('ix_raw_scrape_result_parsed', table_name='raw_scrape_result')
    op.drop_index('ix_raw_scrape_result_job_id', table_name='raw_scrape_result')
    op.drop_index('ix_raw_scrape_result_account_id', table_name='raw_scrape_result')
    op.drop_table('raw_scrape_result')
    op.drop_index('ix_job_queue_item_status', table_name='job_queue_item')
    op.drop_index('ix_job_queue_item_priority', table_name='job_queue_item')
    op.drop_index('ix_job_queue_item_job_id', table_name='job_queue_item')
    op.drop_table('job_queue_item')
    op.drop_index('ix_job_event_job_id_sequence', table_name='job_event')
    op.drop_index('ix_job_event_job_id', table_name='job_event')
    op.drop_table('job_event')
    op.drop_index('ix_cross_platform_link_target_platform', table_name='cross_platform_link')
    op.drop_index('ix_cross_platform_link_account_id', table_name='cross_platform_link')
    op.drop_table('cross_platform_link')
    op.drop_index('ix_proxy_record_last_used_at', table_name='proxy_record')
    op.drop_index('ix_proxy_record_is_alive', table_name='proxy_record')
    op.drop_index('ix_proxy_record_host_port', table_name='proxy_record')
    op.drop_table('proxy_record')
    op.drop_index('ix_crawl_job_status', table_name='crawl_job')
    op.drop_index('ix_crawl_job_created_at', table_name='crawl_job')
    op.drop_table('crawl_job')
    op.drop_index('ix_account_scraped_at', table_name='account')
    op.drop_index('ix_account_scrape_depth', table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
