"""add tweet table

Revision ID: b26e32925613
Revises: 9ed9487c073e
Create Date: 2026-06-22 15:29:29.217066

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b26e32925613'
down_revision: str | Sequence[str] | None = '9ed9487c073e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('tweet_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_to', sa.String(), nullable=True),
    sa.Column('quote_url', sa.String(), nullable=True),
    sa.Column('retweeted_from', sa.String(), nullable=True),
    sa.Column('geo_location', sa.String(), nullable=True),
    sa.Column('mentions', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('hashtags', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'tweet_id', name='uq_tweet_account_tweet_id')
    )
    op.create_index('ix_tweet_account_id', 'tweet', ['account_id'], unique=False)
    op.create_index('ix_tweet_timestamp', 'tweet', ['timestamp'], unique=False)
    op.create_index('ix_tweet_tweet_id', 'tweet', ['tweet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tweet_tweet_id', table_name='tweet')
    op.drop_index('ix_tweet_timestamp', table_name='tweet')
    op.drop_index('ix_tweet_account_id', table_name='tweet')
    op.drop_table('tweet')
    # ### end Alembic commands ###
